name: CI + CD

on:
  push:
    branches: [ main-v1.0.1 ]
  workflow_dispatch:


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo building the app 
    
  DeployDev:
    name: Deploy to Dev
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: DEV
      url: 'http://www.dev.kredibot.com'
    steps:
      - name: Deploy
        run: echo deployed to dev 
    
            
  DeployProd:
    name: Deploy to Production 
    needs: [DeployDev]
    runs-on: ubuntu-latest
    environment: 
      name: PRODUCTION
      url: 'http://www.kredibot.com'
    steps:
      - name: Deploy
        run: echo deployed to production
